stages:
  - check
  - build
  - release

image: cr.vertiv.life/library/golang:1.9-alpine

before_script:
  - CI_PROJECT_URL=github.com/terraform-providers/terraform-provider-azurerm/azurerm setup-project
  - dep ensure

check:
  stage: check
  script:
    - make --file=Makefile vet
    - make --file=Makefile test
  except:
    - master
    - tags

build:
  stage: build
  variables:
    VERSION: $CI_COMMIT_TAG
  script:
    - make --file=Makefile build
  artifacts:
    name: terraform-provider-azurerm
    paths:
      - dist
    expire_in: 1h
  only:
    - master
    - tags

release:
  stage: release
  image: cr.vertiv.life/library/deploy-helper
  before_script:
    - apk --update add make
  script:
    - mc config host add vertiv https://s3.vertiv.life vertivart "${ACCOUNT_KEY}"
    - make --file=Makefile dist
    - mc cp dist/*.tar.gz vertiv/${CI_PROJECT_NAME}/
  only:
    - tags