stages:
  - check
  - build
  - release

image: cr.vertiv.life/library/golang:1.9-alpine

before_script:
  - CI_PROJECT_URL=github.com/terraform-providers/terraform-provider-azurerm setup-project

check:
  stage: check
  script:
    - make vet -f makefile
    - make test -f makefile
  except:
    - master
    - tags

build:
  stage: build
  variables:
    VERSION: $CI_COMMIT_TAG
  script:
    - make build -f makefile
  artifacts:
    name: terraform-provider-azurerm
    paths:
      - dist
    expire_in: 1h
  only:
    - master
    - tags

release:
  stage: release
  image: cr.vertiv.life/library/deploy-helper
  before_script:
    - apk --update add make
  script:
    - mc config host add vertiv https://s3.vertiv.life vertivart "${ACCOUNT_KEY}"
    - make dist -f makefile
    - mc cp dist/*.tar.gz vertiv/${CI_PROJECT_NAME}/
  only:
    - tags